c_paint_user:
    resource: "@CPaintUserBundle/Controller/"
    type:     annotation
    prefix:   /

cpaint_drawing:
    resource: "@CPaintDrawingBundle/Controller/"
    type:     annotation
    prefix:   /

cpaint_default:
    resource: "@CPaintDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

cpaint_api:
    resource: "@CPaintApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

drawings:
    type:     rest
    resource: CPaint\ApiBundle\Controller\DrawingsController
    prefix: /api/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
